wandb_version: 1

Baseline model:
  desc: null
  value: resnet18
Baseline dataset:
  desc: null
  value: ImageNet1k
Dataset:
  desc: null
  value: ISIC2019-Clean
epochs:
  desc: null
  value: 100
batch_size:
  desc: null
  value: 256
warmup_epochs:
  desc: null
  value: 5
Warmup lr:
  desc: null
  value: 0.001
cooldown_epochs:
  desc: null
  value: 10
patience_epochs:
  desc: null
  value: 10
lr_scheduler:
  desc: null
  value: cosine
lr:
  desc: null
  value: 0.005
min_lr:
  desc: null
  value: 0.0001
drop:
  desc: null
  value: 0.0
weight_decay:
  desc: null
  value: 0.05
optimizer:
  desc: null
  value: adamw
momentum:
  desc: null
  value: 0.9
seed:
  desc: null
  value: 42
class_weights:
  desc: null
  value: None
early_stopping_patience:
  desc: null
  value: 12
early_stopping_delta:
  desc: null
  value: 0.0
model_ema:
  desc: null
  value: true
Batch_augmentation:
  desc: null
  value: false
Loss_scaler:
  desc: null
  value: false
PC:
  desc: null
  value: Server
_wandb:
  desc: null
  value:
    python_version: 3.8.8
    cli_version: 0.15.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1707332371.636084
    t:
      1:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      3:
      - 16
      - 23
      4: 3.8.8
      5: 0.15.3
      8:
      - 3
      - 5
